import 'package:food_furniture_app/util/dummy_data/model/food.dart';
import 'package:food_furniture_app/util/dummy_data/model/furniture.dart';
import 'package:food_furniture_app/util/dummy_data/model/product.dart';

class DummyData {
  List<Product> get food => [
        Food(
            brand: "Heinz",
            type: "pasta",
            image: "assets/images/food_images/pasta/pasta_1.jpeg",
            price: 7.99,
            product: "Spaghetti with Sausages",
            weight: 400,
            weightType: 0,
            rating: 4.3,
            description:
                "Sausage Spaghetti flavored with tomato sauce and special spices",
            ingredients: [
              "Tomato",
              "Flour",
              "Salt",
              "Pepper",
              "Egg",
              "Sausage"
            ]),
        Food(
            brand: "Heinz",
            type: "pasta",
            image: "assets/images/food_images/pasta/pasta_2.jpeg",
            price: 7.99,
            product: "Spaghetti Bolognese",
            weight: 400,
            weightType: 0,
            rating: 3.8,
            description:
                "Spaghetti with Bolognese sauce prepared with minced meat, celery, tomatoes and special spices",
            ingredients: [
              "Tomato",
              "Flour",
              "Salt",
              "Pepper",
              "Egg",
              "Meet",
              "Celery"
            ]),
        Food(
            brand: "Heinz",
            type: "pasta",
            image: "assets/images/food_images/pasta/pasta_3.jpeg",
            price: 7.99,
            product: "Macaroni Cheese",
            rating: 4,
            weight: 400,
            weightType: 0,
            description:
                "Cheese maxaroni with special sauce prepared with three kinds of cheese",
            ingredients: [
              "Flour",
              "Salt",
              "Pepper",
              "Egg",
              "Cheddar",
              "Parmesan",
              "Mozzarella",
              "Milk"
            ]),
        Food(
            brand: "Tesco",
            type: "pasta",
            image: "assets/images/food_images/pasta/pasta_4.jpeg",
            price: 4.99,
            product: "Macaroni Cheese in Sauce",
            weight: 300,
            rating: 1,
            weightType: 0,
            description:
                "Cheese maxaroni with special sauce prepared with milk and cheese",
            ingredients: ["Flour", "Salt", "Pepper", "Egg", "Cheddar", "Milk"]),
        Food(
            brand: "Tesco",
            type: "pasta",
            image: "assets/images/food_images/pasta/pasta_5.jpeg",
            price: 4.99,
            product: "Spaghetti Rings&Sausages",
            weight: 300,
            weightType: 0,
            rating: 4.2,
            description:
                "Sausage Spaghetti flavored with tomato sauce and special spices",
            ingredients: [
              "Tomato",
              "Flour",
              "Salt",
              "Pepper",
              "Egg",
              "Sausage"
            ]),
        Food(
            brand: "Tesco",
            type: "pasta",
            image: "assets/images/food_images/pasta/pasta_6.jpeg",
            price: 4.99,
            product: "Spaghetti Rings",
            weight: 300,
            rating: 4.3,
            weightType: 0,
            description:
                "Spaghetti flavored with tomato sauce and special spices",
            ingredients: ["Tomato", "Flour", "Salt", "Pepper", "Egg"]),
        Food(
            brand: "Princes",
            type: "fish",
            image: "assets/images/food_images/fish/fish_1.jpeg",
            price: 34.55,
            product: "Drained Tuna Steak",
            weight: 500,
            weightType: 0,
            rating: 4.5,
            description:
                "Tuna steak flavored with spices in a little sunflower oil",
            ingredients: ["Tuna", "Salt", "Pepper", "Sunflower Oil"]),
        Food(
            brand: "Princes",
            type: "fish",
            image: "assets/images/food_images/fish/fish_2.jpeg",
            price: 32.55,
            product: "Drained Tuna Steak",
            weight: 500,
            rating: 4.7,
            weightType: 0,
            description:
                "Tuna steak flavored with spices in a little spring water",
            ingredients: ["Tuna", "Salt", "Pepper", "Spring Water"]),
        Food(
            brand: "John West",
            type: "fish",
            image: "assets/images/food_images/fish/fish_3.jpeg",
            price: 12.5,
            product: "Sardines with Olive Oil",
            weight: 200,
            rating: 2.5,
            weightType: 0,
            description: "Boneless Sardines flavored with spices in olive oil",
            ingredients: ["Sardine", "Salt", "Pepper", "Olive Oil"]),
        Food(
            brand: "Tesco",
            type: "fish",
            image: "assets/images/food_images/fish/fish_4.jpeg",
            price: 12.5,
            product: "Drained Tuna Steaks",
            weight: 200,
            rating: 3.7,
            weightType: 0,
            description:
                "Tuna steak flavored with spices with a little spring water",
            ingredients: ["Tuna", "Salt", "Pepper", "Spring Water"]),
        Food(
            brand: "Tesco",
            type: "fish",
            image: "assets/images/food_images/fish/fish_5.jpeg",
            price: 12.5,
            product: "Drained Tuna Steak",
            weight: 200,
            rating: 5,
            weightType: 0,
            description:
                "Tuna steak flavored with spices in a little sunflower oil",
            ingredients: ["Tuna", "Salt", "Pepper", "Sunflower Oil"]),
        Food(
            brand: "Princes",
            type: "fish",
            image: "assets/images/food_images/fish/fish_6.jpeg",
            price: 13.8,
            rating: 4.5,
            product: "Drained Red Salmon",
            weight: 200,
            weightType: 0,
            description: "Red Salmon flavored with spices",
            ingredients: [
              "Salmon",
              "Salt",
              "Pepper",
            ]),
        Food(
            brand: "Cadbury",
            type: "chocolate",
            image: "assets/images/food_images/chocolates/chocolates_2.jpeg",
            price: 6.45,
            product: "Dairy Milk Chocolate",
            weight: 80,
            rating: 3.5,
            weightType: 0,
            description:
                "Chocolate produced with fresh milk and special cocoa beans",
            ingredients: ["Cocoa", "Milk", "Sugar"]),
        Food(
            brand: "Ferrero Rocher",
            type: "chocolate",
            image: "assets/images/food_images/chocolates/chocolates_1.jpeg",
            price: 37.99,
            rating: 2.4,
            product: "Ferrero Rocher Cholocate",
            weight: 24,
            weightType: 2,
            description:
                "Flavor harmony consisting of chocolate, wafer and hazelnut layers",
            ingredients: ["Cocoa", "Milk", "Sugar", "Nut", "Flour"]),
        Food(
            brand: "Nestle",
            type: "chocolate",
            image: "assets/images/food_images/chocolates/chocolates_3.jpeg",
            price: 27.77,
            product: "After Eight",
            weight: 300,
            weightType: 0,
            rating: 3.4,
            description: "Dark chocolate with mint filling",
            ingredients: ["Cocoa", "Milk", "Sugar", "Mint", "Flour"]),
        Food(
            brand: "Kitkat",
            type: "chocolate",
            image: "assets/images/food_images/chocolates/chocolates_4.jpeg",
            price: 6.25,
            product: "Chunky",
            weight: 80,
            rating: 4.2,
            weightType: 0,
            description: "Crispy wafer and chocolate coating",
            ingredients: ["Cocoa", "Milk", "Sugar", "Flour"]),
        Food(
            brand: "Cadbury",
            type: "chocolate",
            image: "assets/images/food_images/chocolates/chocolates_5.jpeg",
            price: 8.75,
            product: "Crunchie",
            weight: 4,
            rating: 3.5,
            weightType: 2,
            description: "Crispy wafer and chocolate coating",
            ingredients: ["Cocoa", "Milk", "Sugar", "Flour", "Crunch"]),
        Food(
            brand: "Tesco",
            type: "chocolate",
            image: "assets/images/food_images/chocolates/chocolates_6.jpeg",
            price: 12.5,
            product: "Milk Chocolate",
            weight: 100,
            rating: 3.2,
            weightType: 0,
            description: "Silky&Smooth Milky Chocolate",
            ingredients: ["Cocoa", "Milk", "Sugar", "Flour"]),
        Food(
            brand: "Jacob's",
            type: "biscuit",
            image: "assets/images/food_images/biscuit/biscuit_1.png",
            price: 7.5,
            product: "Cornish Wafers",
            rating: 4.1,
            weight: 100,
            weightType: 0,
            description: "Gluten-free waffles made with cornmeal",
            ingredients: ["Cornmeal", "Milk", "Sugar"]),
        Food(
            brand: "Tesco",
            type: "biscuit",
            image: "assets/images/food_images/biscuit/biscuit_3.png",
            price: 22.75,
            rating: 4.1,
            product: "Biscuits for cheese",
            weight: 250,
            weightType: 0,
            description: "Flavor befitting cheese",
            ingredients: ["Flour", "Milk", "Salt"]),
        Food(
            brand: "Tesco",
            type: "biscuit",
            image: "assets/images/food_images/biscuit/biscuit_4.png",
            price: 8.99,
            rating: 3.6,
            product: "Lightly Salted Corns",
            weight: 100,
            weightType: 0,
            description: "Pretzels flavored with sea salt",
            ingredients: ["Flour", "Milk", "Sea Salt"]),
        Food(
            brand: "Carrs",
            type: "biscuit",
            image: "assets/images/food_images/biscuit/biscuit_5.png",
            price: 10,
            rating: 3.9,
            product: "Melts",
            weight: 100,
            weightType: 0,
            description: "Cheese Pretzels",
            ingredients: ["Flour", "Milk", "Cheese", "Salt"]),
        Food(
            brand: "Tesco",
            type: "biscuit",
            image: "assets/images/food_images/biscuit/biscuit_6.png",
            price: 15.6,
            product: "Mini Breadsticks",
            weight: 124,
            rating: 5,
            weightType: 0,
            description: "Breadsticks",
            ingredients: ["Flour", "Salt"]),
        Food(
            brand: "Nairn's",
            type: "biscuit",
            image: "assets/images/food_images/biscuit/biscuit_7.png",
            price: 32.45,
            rating: 3.4,
            product: "Rough Outcakes",
            weight: 291,
            weightType: 0,
            description: "Mini oat cakes with high fiber content",
            ingredients: ["Oat", "Oil", "Salt"]),
        Food(
            brand: "Nairn's",
            type: "biscuit",
            image: "assets/images/food_images/biscuit/biscuit_8.png",
            price: 32.45,
            rating: 4.3,
            product: "Fine Milled Outcakes",
            weight: 250,
            weightType: 0,
            description: "Mini oat cakes with high fiber content",
            ingredients: ["Oat", "Oil", "Salt"]),
        Food(
            brand: "Nairn's",
            type: "biscuit",
            image: "assets/images/food_images/biscuit/biscuit_9.png",
            price: 32.45,
            product: "Cheese Outcakes",
            weight: 200,
            rating: 4.4,
            weightType: 0,
            description: "Mini oat cakes with high fiber content",
            ingredients: ["Oat", "Oil", "Cheese", "Salt"]),
        Food(
            brand: "Weetabix",
            type: "cereal",
            image: "assets/images/food_images/cereal/cereal_1.jpeg",
            price: 22.95,
            product: "Crispy Minis",
            weight: 850,
            rating: 5,
            weightType: 0,
            description: "Chocolate Chip",
            ingredients: ["Chocolate", "Oat", "Sugar"]),
        Food(
            brand: "Kellogg's",
            type: "cereal",
            image: "assets/images/food_images/cereal/cereal_2.jpeg",
            price: 54.79,
            product: "Crunchy Nut",
            weight: 1,
            rating: 3.2,
            weightType: 1,
            description: "Chocolate Chip",
            ingredients: [
              "Oat",
              "Sugar",
              "Nut",
              "Corn",
              "Honey",
            ]),
        Food(
            brand: "Kellogg's",
            type: "cereal",
            image: "assets/images/food_images/cereal/cereal_3.jpeg",
            price: 27.95,
            rating: 4.8,
            product: "Special K",
            weight: 500,
            weightType: 0,
            description: "Original corn chip",
            ingredients: ["Corn", "Oat", "Sugar"]),
        Food(
            brand: "Kellogg's",
            type: "cereal",
            image: "assets/images/food_images/cereal/cereal_4.jpeg",
            price: 45.95,
            product: "Frosties",
            weight: 750,
            weightType: 0,
            rating: 3.8,
            description: "Corn chip",
            ingredients: ["Chocolate", "Oat", "Sugar"]),
        Food(
            brand: "Ready Brek",
            type: "cereal",
            image: "assets/images/food_images/cereal/cereal_5.jpeg",
            price: 22.95,
            product: "Crispy Minis",
            weight: 450,
            rating: 2.9,
            weightType: 0,
            description: "Chocolate Chip",
            ingredients: ["Oat", "Sugar"]),
        Food(
            brand: "Kellogg's",
            type: "cereal",
            image: "assets/images/food_images/cereal/cereal_6.jpeg",
            price: 22.95,
            rating: 4.7,
            product: "Rice Crispies",
            weight: 510,
            weightType: 0,
            description: "Rice crunch",
            ingredients: ["Rice"]),
      ];

  List<Product> get furniture => [
        Furniture(
            brand: "Vitra",
            type: "chair",
            image: "assets/images/furniture_images/chair/chair_1_brown.jpeg",
            price: 124.99,
            rating: 3.9,
            product: "Luna Estona",
            color: "brown",
            colorOptions: ["white", "black", "grey"],
            description:
                "The perfect harmony of wood with the seats made of gray fabric.",
            productId: "luna_estona_brown",
            productBaseId: "luna_estona"),
        Furniture(
            brand: "Vitra",
            type: "chair",
            image: "assets/images/furniture_images/chair/chair_1_black.jpeg",
            price: 124.99,
            rating: 3.7,
            product: "Luna Estona",
            color: "black",
            colorOptions: ["brown", "grey", "white"],
            description:
                "The perfect harmony of wood with the seats made of gray fabric.",
            productId: "luna_estona_black",
            productBaseId: "luna_estona"),
        Furniture(
            brand: "Vitra",
            type: "chair",
            image: "assets/images/furniture_images/chair/chair_1_grey.jpeg",
            price: 124.99,
            product: "Luna Estona",
            rating: 4.9,
            color: "grey",
            colorOptions: ["white", "black", "brown"],
            description:
                "The perfect harmony of wood with the seats made of gray fabric.",
            productId: "luna_estona_grey",
            productBaseId: "luna_estona"),
        Furniture(
            brand: "Ikea",
            type: "chair",
            image: "assets/images/furniture_images/chair/chair_2_brown.jpeg",
            price: 179.99,
            rating: 4.6,
            product: "Ingolf",
            color: "brown",
            colorOptions: ["white", "black", "grey"],
            description: "Modern style made with special foal feathers",
            productId: "ingolf_brown",
            productBaseId: "ingolf"),
        Furniture(
            brand: "Ikea",
            type: "chair",
            image: "assets/images/furniture_images/chair/chair_2_black.jpeg",
            price: 179.99,
            rating: 3.6,
            product: "Ingolf",
            color: "black",
            colorOptions: ["white", "grey", "brown"],
            description: "Modern style made with special foal feathers",
            productId: "ingolf_black",
            productBaseId: "ingolf"),
        Furniture(
            brand: "Ikea",
            type: "chair",
            image: "assets/images/furniture_images/chair/chair_1_grey.jpeg",
            price: 179.99,
            rating: 2.9,
            product: "Ingolf",
            color: "grey",
            colorOptions: ["white", "black", "brown"],
            description: "Modern style made with special foal feathers",
            productId: "ingolf_grey",
            productBaseId: "ingolf"),
        Furniture(
            brand: "Ikea",
            type: "chair",
            rating: 3.6,
            image: "assets/images/furniture_images/chair/chair_2_white.jpeg",
            price: 179.99,
            product: "Ingolf",
            color: "white",
            colorOptions: ["grey", "black", "brown"],
            description: "TModern style made with special foal feathers",
            productId: "ingolf_white",
            productBaseId: "ingolf"),
        Furniture(
            brand: "Banio",
            type: "chair",
            image: "assets/images/furniture_images/chair/chair_3_white.jpeg",
            price: 78.75,
            product: "Teodores",
            color: "white",
            rating: 4.2,
            colorOptions: ["red", "black"],
            description: "The elegance of wood with the seat made of durable plastic",
            productId: "teodores_white",
            productBaseId: "teodores"),
        Furniture(
            brand: "Banio",
            type: "chair",
            image: "assets/images/furniture_images/chair/chair_3_red.jpeg",
            price: 78.75,
            rating: 1,
            product: "Teodores",
            color: "red",
            colorOptions: ["white", "black"],
            description: "The elegance of wood with the seat made of durable plastic",
            productId: "teodores_red",
            productBaseId: "teodores"),
        Furniture(
            brand: "Banio",
            type: "chair",
            image: "assets/images/furniture_images/chair/chair_3_black.jpeg",
            price: 78.75,
            rating: 3.7,
            product: "Teodores",
            color: "black",
            colorOptions: ["red", "white"],
            description: "The elegance of wood with the seat made of durable plastic",
            productId: "teodores_black",
            productBaseId: "teodores"),
        Furniture(
            brand: "Ikea",
            type: "chair",
            rating: 4.9,
            image: "assets/images/furniture_images/chair/chair_4_black.jpeg",
            price: 99.99,
            product: "Lerhamn",
            color: "black",
            colorOptions: ["grey", "cream"],
            description: "Collar fabric, specially designed seat and harmony of wood",
            productId: "lerhamn_black",
            productBaseId: "lerhamn"),
        Furniture(
            brand: "Ikea",
            type: "chair",
            image: "assets/images/furniture_images/chair/chair_4_cream.jpeg",
            price: 99.99,
            rating: 3.6,
            product: "Lerhamn",
            color: "cream",
            colorOptions: ["grey", "black"],
            description: "Collar fabric, specially designed seat and harmony of wood",
            productId: "lerhamn_cream",
            productBaseId: "lerhamn"),
        Furniture(
            brand: "Ikea",
            type: "chair",
            rating: 3.5,
            image: "assets/images/furniture_images/chair/chair_4_grey.jpeg",
            price: 99.99,
            product: "Lerhamn",
            color: "grey",
            colorOptions: ["cream", "black"],
            description: "Collar fabric, specially designed seat and harmony of wood",
            productId: "lerhamn_grey",
            productBaseId: "lerhamn"),
        Furniture(
            brand: "Ikea",
            type: "chair",
            image: "assets/images/furniture_images/chair/chair_5_brown.jpeg",
            price: 99.99,
            rating: 4.1,
            product: "Terje",
            color: "brown",
            colorOptions: ["white", "grey"],
            description: "Specially designed seat and harmony of wood",
            productId: "terje_brown",
            productBaseId: "terje"),
        Furniture(
            brand: "Ikea",
            type: "chair",
            image: "assets/images/furniture_images/chair/chair_5_grey.jpeg",
            price: 99.99,
            rating: 2.8,
            product: "Terje",
            color: "grey",
            colorOptions: ["white", "brown"],
            description: "Specially designed seat and harmony of wood",
            productId: "terje_grey",
            productBaseId: "terje"),
        Furniture(
            brand: "Ikea",
            type: "chair",
            rating: 3.6,
            image: "assets/images/furniture_images/chair/chair_5_white.jpeg",
            price: 99.99,
            product: "Terje",
            color: "white",
            colorOptions: ["grey", "brown"],
            description: "Specially designed seat and harmony of wood",
            productId: "terje_white",
            productBaseId: "terje"),
        Furniture(
            brand: "Ikea",
            type: "chair",
            image: "assets/images/furniture_images/chair/chair_6.jpeg",
            price: 99.99,
            rating: 8.5,
            product: "Nisse",
            color: "black",
            colorOptions: [],
            description: "Specially designed seat and harmony of wood",
            productId: "nisse_black",
            productBaseId: ""),
        Furniture(
            brand: "Vitra",
            type: "table",
            image: "assets/images/furniture_images/table/table_1_white.jpeg",
            price: 224.99,
            rating: 3.3,
            product: "Vangsta",
            color: "white",
            colorOptions: ["black"],
            description: "Dinner table",
            productId: "vangsta_white",
            productBaseId: "vangsta"),
        Furniture(
            brand: "Vitra",
            type: "table",
            image: "assets/images/furniture_images/table/table_1_black.jpeg",
            price: 224.99,
            product: "Vangsta",
            color: "black",
            rating: 2.3,
            colorOptions: ["white"],
            description: "Dinner table",
            productId: "vangsta_black",
            productBaseId: "vangsta"),
        Furniture(
            brand: "Asona",
            type: "table",
            image: "assets/images/furniture_images/table/table_2_white.jpeg",
            price: 129.9,
            rating: 2.3,
            product: "Ingatorp",
            color: "white",
            colorOptions: ["black"],
            description: "Circular dinner table",
            productId: "ingatorp_white",
            productBaseId: "ingatorp"),
        Furniture(
            brand: "Asona",
            type: "table",
            image: "assets/images/furniture_images/table/table_2_black.jpeg",
            price: 129.9,
            rating: 1.5,
            product: "Ingatorp",
            color: "black",
            colorOptions: ["white"],
            description: "Circular dinner table",
            productId: "ingatorp_black",
            productBaseId: "ingatorp"),
        Furniture(
            brand: "Asona",
            type: "table",
            image: "assets/images/furniture_images/table/table_3_cream.jpeg",
            price: 176.84,
            product: "Norben",
            color: "cream",
            rating: 1.6,
            colorOptions: ["black"],
            description: "Circular dinner table",
            productId: "norben_cream",
            productBaseId: "norben"),
        Furniture(
            brand: "Asona",
            type: "table",
            image: "assets/images/furniture_images/table/table_3_black.jpeg",
            price: 176.84,
            rating: 4.7,
            product: "Norben",
            color: "black",
            colorOptions: ["cream"],
            description: "Circular dinner table",
            productId: "norben_black",
            productBaseId: "norben"),
        Furniture(
            brand: "Ikea",
            type: "table",
            image: "assets/images/furniture_images/table/table_5_brown.jpeg",
            price: 198.25,
            rating: 3.5,
            product: "Lisabo",
            color: "brown",
            colorOptions: ["cream"],
            description: "Eye-catching with its stylish leg design",
            productId: "lisabo_brown",
            productBaseId: "lisabo"),
        Furniture(
            brand: "Ikea",
            type: "table",
            image: "assets/images/furniture_images/table/table_5_cream.jpeg",
            price: 198.25,
            product: "Lisabo",
            rating: 3.6,
            color: "cream",
            colorOptions: ["brown"],
            description: "Eye-catching with its stylish leg design",
            productId: "lisabo_cream",
            productBaseId: "lisabo"),
        Furniture(
            brand: "Ikea",
            type: "dresser",
            image: "assets/images/furniture_images/dresser/dresser_1.jpeg",
            price: 112.76,
            rating: 4.6,
            product: "Platsa",
            color: "grey",
            colorOptions: [],
            description: "Eye-catching design with stone look",
            productId: "platsa_grey",
            productBaseId: ""),
        Furniture(
            brand: "Ikea",
            type: "dresser",
            image: "assets/images/furniture_images/dresser/dresser_2.jpeg",
            price: 112.76,
            rating: 4.7,
            product: "Arken",
            color: "white",
            colorOptions: [],
            description: "White, elegance dresser",
            productId: "arken_white",
            productBaseId: ""),
        Furniture(
            brand: "Ikea",
            type: "dresser",
            image: "assets/images/furniture_images/dresser/dresser_3.jpeg",
            price: 177.45,
            rating: 4.2,
            product: "Galadriel",
            color: "black",
            colorOptions: [],
            description: "Eye-catching design with stone look",
            productId: "galadriel_black",
            productBaseId: ""),
        Furniture(
            brand: "Arwen",
            type: "sofa",
            image: "assets/images/furniture_images/sofa/sofa_1_grey.jpeg",
            price: 177.45,
            rating: 2.8,
            product: "Stella",
            color: "grey",
            colorOptions: ["white", "brown", "cream"],
            description: "Adds elegance to homes with its soft waterproof fabric",
            productId: "arwen_grey",
            productBaseId: "arwen"),
        Furniture(
            brand: "Arwen",
            type: "sofa",
            image: "assets/images/furniture_images/sofa/sofa_1_cream.jpeg",
            price: 177.45,
            rating: 3.6,
            product: "Stella",
            color: "cream",
            colorOptions: ["white", "brown", "grey"],
            description: "Adds elegance to homes with its soft waterproof fabric",
            productId: "arwen_cream",
            productBaseId: "arwen"),
        Furniture(
            brand: "Arwen",
            type: "sofa",
            image: "assets/images/furniture_images/sofa/sofa_1_white.jpeg",
            price: 177.45,
            product: "Stella",
            rating: 2.5,
            color: "white",
            colorOptions: ["brown", "cream", "grey"],
            description: "Adds elegance to homes with its soft waterproof fabric",
            productId: "arwen_white",
            productBaseId: "arwen"),
        Furniture(
            brand: "Arwen",
            type: "sofa",
            image: "assets/images/furniture_images/sofa/sofa_1_brown.jpeg",
            price: 177.45,
            rating: 3.5,
            product: "Stella",
            color: "brown",
            colorOptions: ["white", "cream", "grey"],
            description: "Adds elegance to homes with its soft waterproof fabric",
            productId: "arwen_brown",
            productBaseId: "arwen"),
        Furniture(
            brand: "Vitra",
            type: "sofa",
            image: "assets/images/furniture_images/sofa/sofa_2_yellow.jpeg",
            price: 278.97,
            product: "Libre",
            rating: 4.6,
            color: "yellow",
            colorOptions: ["grey", "dark_grey", "blue"],
            description: "Adds elegance to homes with its soft waterproof fabric",
            productId: "libre_yellow",
            productBaseId: "libre"),
        Furniture(
            brand: "Vitra",
            type: "sofa",
            image: "assets/images/furniture_images/sofa/sofa_2_grey.jpeg",
            price: 278.97,
            rating: 3.8,
            product: "Libre",
            color: "grey",
            colorOptions: ["dark_grey", "yellow", "blue"],
            description: "Adds elegance to homes with its soft waterproof fabric",
            productId: "libre_grey",
            productBaseId: "libre"),
        Furniture(
            brand: "Vitra",
            type: "sofa",
            image: "assets/images/furniture_images/sofa/sofa_2_blue.jpeg",
            price: 278.97,
            product: "Libre",
            rating: 4.7,
            color: "blue",
            colorOptions: ["grey", "dark_grey", "yellow"],
            description: "Adds elegance to homes with its soft waterproof fabric",
            productId: "libre_blue",
            productBaseId: "libre"),
        Furniture(
            brand: "Vitra",
            type: "sofa",
            image: "assets/images/furniture_images/sofa/sofa_2_dark_grey.jpeg",
            price: 278.97,
            rating: 4.8,
            product: "Libre",
            color: "dark_grey",
            colorOptions: ["grey", "yellow", "blue"],
            description: "Adds elegance to homes with its soft waterproof fabric",
            productId: "libre_dark_grey",
            productBaseId: "libre"),
        Furniture(
            brand: "Ikea",
            type: "sofa",
            rating: 4.5,
            image: "assets/images/furniture_images/sofa/sofa_3_grey.jpeg",
            price: 69.58,
            product: "Vimle",
            color: "grey",
            colorOptions: ["blue", "yellow"],
            description: "Adds elegance to homes with its soft waterproof fabric",
            productId: "vimle_grey",
            productBaseId: "vimle"),
        Furniture(
            brand: "Ikea",
            type: "sofa",
            image: "assets/images/furniture_images/sofa/sofa_3_blue.jpeg",
            price: 69.58,
            product: "Vimle",
            color: "blue",
            rating: 3.9,
            colorOptions: ["yellow", "grey"],
            description: "Adds elegance to homes with its soft waterproof fabric",
            productId: "vimle_blue",
            productBaseId: "vimle"),
        Furniture(
            brand: "Ikea",
            type: "sofa",
            image: "assets/images/furniture_images/sofa/sofa_3_yellow.jpeg",
            price: 69.58,
            rating: 4.6,
            product: "Vimle",
            color: "yellow",
            colorOptions: ["blue", "grey"],
            description: "Adds elegance to homes with its soft waterproof fabric",
            productId: "vimle_yellow",
            productBaseId: "vimle"),
      ];

  List<String> get foodCategories => [
    "pasta",
    "fish",
    "chocolate",
    "biscuit",
    "cereal"
  ];

  List<String> get furnitureCategories => [
    "chair",
    "table",
    "sofa",
    "dresser"
  ];
}
